name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  syncimages:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repos
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          #!/usr/bin/env bash
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker pull quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
          docker tag quay.io/strimzi/kafka:0.43.0-kafka-3.8.0 registry.cn-hangzhou.aliyuncs.com/jlgu/es:kafka-0.43.0-kafka-3.8.0
          docker push registry.cn-hangzhou.aliyuncs.com/jlgu/es:kafka-0.43.0-kafka-3.8.0
