name: Sync Docker Image

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        logout: false 
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy registry.hub.docker.com/loggieio/loggie:v1.4.0 docker://registry.cn-hangzhou.aliyuncs.com/jlgu/loggie:v1.4.0
