name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  syncimages:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repos
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
  
      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          #!/usr/bin/env bash
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker pull registry.k8s.io/debian-base:v2.0.0
          docker tag registry.k8s.io/debian-base:v2.0.0 registry.cn-hangzhou.aliyuncs.com/jlgu/es:v2.0.0
          docker push registry.cn-hangzhou.aliyuncs.com/jlgu/es:v2.0.0
          # skopeo copy --all docker://registry.hub.docker.com/loggieio/loggie:v1.4.0 docker://registry.cn-hangzhou.aliyuncs.com/jlgu/loggie:v1.4.0
